name: finanzas_lite
description: "Flutter finance app developed for university"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  get: ^4.7.2
  flutter_svg: ^2.2.2
  syncfusion_flutter_charts: ^31.2.5
  intl: ^0.20.2
  delightful_toast: ^1.1.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/svgs/categoryIcons/
    - assets/svgs/navbar/
    - assets/svgs/accounts/
